spring:
  datasource:
    url: jdbc:h2:file:./target/db/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2.console.enabled: true